### ISSUE TITLE
Missing fossils image

### ISSUE THREAD

**Issue by jimmyorz** [MirayXS/ACNH-IMAGEZIP#2]
I found that the fossils image is missing "plesio torso".
It was used with the wrong file name "plesio body"

**Comment by MirayXS** [comment]
Fixed!

### <a href="https://github.com/MirayXS/ACNH-IMAGEZIP">:white_check_mark: ACNH-IMAGEZIP</a> (download latest)
###  <a href="https://github.com/MirayXS/ACNHCDN">:white_check_mark:  ACNHCDN</a>
