### ISSUE TITLE
Some image issues

### ISSUE THREAD

**Issue by jimmyorz** [MirayXS/ACNH-IMAGEZIP#3]
[Wrong Filename]
housewares\tone-lion dog.png > stone lion-dog.png

[Missing]
dresses\wedding dress.png
https://acnhcdn.com/1.2.0/FtrIcon/TopsTexOnepieceDressNWedding.png

other\nook miles ticket.png
https://acnhcdn.com/latest/MenuIcon/PlaneTicket.png

other\bell voucher.png
https://acnhcdn.com/latest/MenuIcon/BellExchangeTicket.png

other\DIY recipe.png
Can use existing image, such as Flimsy Axe Recipe, Flimsy Shovel Recipe.

**Comment by MirayXS** [comment]
Wedding Dress was mistaken with: cake dress.png

What do you mean with `...`
`Can use existing image, such as Flimsy Axe Recipe, Flimsy Shovel Recipe.`

**Comment by MirayXS** [comment]
Just figured myself; Needed the DIY recipe image

**Comment by MirayXS** [comment]
# Fixed in latest release
